name: Spaghetti and Hammers
title: Spaghetti and Hammers
description: Personal site of Pedro Rijo (@pedrorijo91). Writing about Scala, Java, Functional Programming, git, and whatever I find time to learn about.
author: Pedro Rijo (@pedrorijo91)
url: https://pedrorijo.com
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
paginate: 8

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: All posts
   url: /tags
 - title: External contributions
   url: /external
 - title: Presentations
   url: /presentations
 - title: Newsletter
   url: https://mailchi.mp/f9d5cd479369/pedrorijo91
   external: true

newsletter: https://mailchi.mp/f9d5cd479369/pedrorijo91

include: [".well-known"]
exclude: [vendor]
